[build]
  publish = "build/web"
  command = "bash scripts/netlify_build.sh"

# SPA routing: send all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: cache built assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/flutter.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 